return {
    -- require('myplugins.interface.colorscheme-plugins.everforest'),
    -- require('myplugins.interface.colorscheme-plugins.nightfox'),
    -- require('myplugins.interface.colorscheme-plugins.material'),
    require('myplugins.interface.colorscheme-plugins.nebulous'),
    -- require('myplugins.interface.colorscheme-plugins.embark'),
    -- require('myplugins.interface.colorscheme-plugins.pinkmare'),
    -- require('myplugins.interface.colorscheme-plugins.tokyodark'),
    -- require('myplugins.interface.colorscheme-plugins.omni'),
    -- require('myplugins.interface.colorscheme-plugins.gloombuddy'),
    -- require('myplugins.interface.colorscheme-plugins.doom-one'),
    -- require('myplugins.interface.colorscheme-plugins.seoul256'),
    -- require('myplugins.interface.colorscheme-plugins.miramare'),
    -- require('myplugins.interface.colorscheme-plugins.oceanic-next'),
    -- require('myplugins.interface.colorscheme-plugins.onedark'),
}
