return {
    -- require('myplugins.interface.colorschemes.everforest'),
    -- require('myplugins.interface.colorschemes.nightfox'),
    -- require('myplugins.interface.colorschemes.material'),
    require('myplugins.interface.colorschemes.nebulous'),
    -- require('myplugins.interface.colorschemes.embark'),
    -- require('myplugins.interface.colorschemes.pinkmare'),
    -- require('myplugins.interface.colorschemes.tokyodark'),
    -- require('myplugins.interface.colorschemes.omni'),
    -- require('myplugins.interface.colorschemes.gloombuddy'),
    -- require('myplugins.interface.colorschemes.doom-one'),
    -- require('myplugins.interface.colorschemes.seoul256'),
    -- require('myplugins.interface.colorschemes.miramare'),
    -- require('myplugins.interface.colorschemes.oceanic-next'),
    -- require('myplugins.interface.colorschemes.onedark'),
}
