return require('vimrc.functions').return_gathered_plugins(
    'myplugins.handy-tools',
    {
        'fzf-lua',
        'fzf-vim',
        'gitsigns',
        'localrc',
        'multi-cursor',
        'printer',
        'snippets',
        'telescope',
        'trailblazer',
        'treesitter-context',
        'localrc-plugins.exrc',
        'localrc-plugins.vim-localrc',
        'codeium-vim',
        'codeium-nvim',
        'wildfire',
    })
